### PR TITLE
Convert tests to regex versions

### PR DESCRIPTION
**Pull request by GravesJake**

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks. Can you remove the implementations of `assertRaises` and `assertWarns` too?

**Comment by GravesJake** [comment]
The ones that don’t contain a `msg` argument?

**Comment by GravesJake** [comment]
Okay, there are a few calls left to the non-reflex versions that don’t contain a `msg ` argument. I’m guessing those should be changed over to refer versions as well then?

**Comment by whitequark** [comment]
I mean these: https://github.com/nmigen/nmigen/blob/c75fa45fd80063ad5681f389fb038d6d98f4f0a0/nmigen/test/utils.py#L31-L46

**Comment by whitequark** [comment]
> I’m guessing those should be changed over to regex versions as well then?

Nope, they should work fine as-is, with no additional changes.

**Comment by whitequark** [comment]
Thank you!

**Pull request merged**
