### PR TITLE
lib.fifo.AsyncFFSynchronizer: check input and output signal width

### PR DESCRIPTION
**Pull request by rroohhh**
wasted more time than I would like to admit due to this :)

### CODE REVIEW

**Review by whitequark — CHANGES_REQUESTED** [review]
A few nits:
 * By convention, all error checking happens at the function entry.
 * The error messages would be easier to read and more consistent with our other error messages if they used `1`, not `one`.

**Comment by rroohhh** [comment]
`async_edge` is also not checked at the function entry, should that be changed aswell?

**Comment by whitequark** [comment]
Yup.

**Review by whitequark — APPROVED** [review]

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
