### PR TITLE
Add r_level and w_level to all FIFOs

### PR DESCRIPTION
**Pull request by awygle**
As described in issue #328

### CODE REVIEW

**Comment by awygle** [comment]
I'm not sure what I screwed up Git-wise that made it ask me to resolve conflicts? If you want me to figure that out and reopen this or something let me know...

**Comment by whitequark** [comment]
> I'm not sure what I screwed up Git-wise that made it ask me to resolve conflicts? If you want me to figure that out and reopen this or something let me know...

Do you think you can rebase it? If not I can take care of it

**Comment by awygle** [comment]
OK, figured it out (it _was_ rebased but I pushed the wrong local branch). Sorry for the noise.

**Comment by whitequark** [comment]
(Why is the branch called "afl"?)

**Comment by awygle** [comment]
"async fifo level"

**Comment by whitequark** [comment]
ah, so not related to american fuzzy lops :)

**Pull request merged**
