### PR TITLE
Improve error message.

### PR DESCRIPTION
**Pull request by BracketMaster**
I run into this error every so often and thought
this could be a more helpful error message.

### CODE REVIEW

**Comment by BracketMaster** [comment]
Assuming anyone else runs into this...

**Comment by BracketMaster** [comment]
Or maybe it could say ``Expected Module not {!r}``?

**Comment by whitequark** [comment]
There's a warning (just below your change) that says the exact same thing, but also points to the `elaborate` function in question which I think should be more useful. Does it not fire for you?

**Comment by BracketMaster** [comment]
Oh. You're right. My fault for not noticing that.

**Comment by whitequark** [comment]
I think I should do *something* with that warning, if people don't notice it, it's as good as not having it in first place...

**Comment by BracketMaster** [comment]
Maybe making it yellow?

**Comment by whitequark** [comment]
That's... hard to do in a good way. Think of the people with white terminals where it'll be unreadable.

**Comment by BracketMaster** [comment]
don't forget, you can change block backgrounds per character.

**Comment by whitequark** [comment]
Right. That will then break on Windows if I use direct escape sequences. And if I want to do it portably it'll be a new dependency and people would complain about *that*. Colors aren't a good solution.

**Comment by BracketMaster** [comment]
This is tricky...
I'm honestly surprised that Windows users use nMigen in 
Windows-Python native, instead of just using Bash-for-Windows.

Is red not a good color? GCC and clang always seem to
emit red regardless of the color scheme. And honestly...
if you have a red terminal background, you're asking for 
trouble...

**Comment by whitequark** [comment]
> I'm honestly surprised that Windows users use nMigen in Windows-Python native, instead of just using Bash-for-Windows.

One thing I've learned is that no matter how liberal my assumptions about the downstream environment are, they are always insufficient to cover the workflow of a surprising amount of people. I think every nMigen tutorial that exists describes a completely different installation method, and that's just on Linux!

**Comment by whitequark** [comment]
Also, Windows Store has an official Python package, so if you just type `python` it prompts you to install that. That package actually works pretty well, so I'm happy to have people follow that path.

**Comment by BracketMaster** [comment]
You can also just ask nMigen users to read errors 
more carefully. Something I should do more often
in general, ha

**Comment by BracketMaster** [comment]
I think I've also seen error messages prefixed with
a sign like ``==> error foo on line 1234``.

**Comment by mithro** [comment]
Here is a horrible suggestion (but /might/ work);
 (a) Collect all warnings as they are emitted.
 (b) On exit, output a summary of the warnings that were emitted (maybe things like the number of each type of warning).
 (c) If a traceback / error occurs, make sure to remit the warnings just before the trace back output.

I would generally say that anything which isn't the in the last few lines of output is going to be very easily ignored?

Maybe you could also having a `-Werror` type thing that is **enabled by default** and people can turn off if needed?

**Comment by whitequark** [comment]
> (c) If a traceback / error occurs, make sure to remit the warnings just before the trace back output.

Just before (i.e. above traceback) or just after (below traceback)?

**Comment by BracketMaster** [comment]
Just to confirm, I was ignoring what was above traceback
as I assumed it _was_ part of the traceback.

UserWarning _was_ above traceback.

So collecting and going below might be better.

**Pull request closed without merging**
