### PR TITLE
setup.py: add "wheel" to setup_requires

### PR DESCRIPTION
**Pull request by alanvgreen**
Fixes problem when installing into a python venv created with

$ python3 -m venv my_env

See https://github.com/m-labs/nmigen/issues/323

### CODE REVIEW

**Comment by whitequark** [comment]
Do you know why this dependency is necessary? It looks like Python is trying to build a wheel here, but the wheel library doesn't exist, which seems like a strange situation.

Does this only happen if you install nmigen from git in virtualenv, and not otherwise?

**Comment by FFY00** [comment]
This does not belong in `setup_requires`, at most, it would be in `extras_require`. Although, I can't reproduce, it seems like a bug in your setup.

**Comment by whitequark** [comment]
I am not able to reproduce either:
```
~$ virtualenv venvtest
Using base prefix '/usr'
New python executable in /home/whitequark/venvtest/bin/python3
Also creating executable in /home/whitequark/venvtest/bin/python
Installing setuptools, pip, wheel...
done.
~$ cd venvtest/
~/venvtest$ . bin/activate
(venvtest) ~/venvtest$ pip install git+https://github.com/nmigen/nmigen.git
Collecting git+https://github.com/nmigen/nmigen.git
  Cloning https://github.com/nmigen/nmigen.git to /tmp/pip-req-build-7qdlu_3v
  Running command git clone -q https://github.com/nmigen/nmigen.git /tmp/pip-req-build-7qdlu_3v
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from nmigen==0.3.dev33+g3346f2c) (46.1.3)
Collecting pyvcd~=0.2.0
  Downloading pyvcd-0.2.1-py2.py3-none-any.whl (17 kB)
Collecting Jinja2~=2.11
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 2.7 MB/s
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl (27 kB)
Building wheels for collected packages: nmigen
  Building wheel for nmigen (setup.py) ... done
  Created wheel for nmigen: filename=nmigen-0.3.dev33+g3346f2c-py3-none-any.whl size=174944 sha256=50252426adffbfbd67f6d9ce85df534d9e1ea16c2872252e56f2e62fb4452bd7
  Stored in directory: /tmp/pip-ephem-wheel-cache-yzut3x95/wheels/82/71/f3/45c024858a8a85e66b358edd4a555c975f96a4e343a1d21e90
Successfully built nmigen
Installing collected packages: pyvcd, MarkupSafe, Jinja2, nmigen
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 nmigen-0.3.dev33+g3346f2c pyvcd-0.2.1
(venvtest) ~/venvtest$
```

**Comment by mithro** [comment]
I think this is a difference between `virtualenv` and `venv` (which are confusingly different tools). `venv` doesn't install wheel into the environment by default it seems while `virtualenv` does. I think `virtualenv --no-wheel` would give you the same behaviour as `venv`.

**Comment by FFY00** [comment]
I created the environment with `venv`, just as described and I was able to install nmigen. Maybe an older version of `venv` didn't install `wheel`?

Either way, there is nothing in nmigen that explicitly requires `wheel`. If `setuptools_scm` is using `wheel` for the installation then `wheel` is its dependency. If `wheel` was an optional dependency of `setuptools_scm` and was required here, then it should be in `setup_requires`, but it isn't.

**Comment by mithro** [comment]
@FFY00 - Your on Arch Linux right? I think the problem is with how Ubuntu / Debianism mangles Python packages. Is `wheel` is an **optional** dependency of `setuptools` / `pip`?

**Comment by FFY00** [comment]
Then it would be a Debian bug. No, `wheel` is not a dependency for either `setuptool_scm` or `pip`, at least in the latest versions.

**Comment by alanvgreen** [comment]
I am seeing the problem on Ubuntu. 

Installation is successful with "wheel" in extra_requires rather than setup_requires.

One aspect of this problem is that wheel appears to be installed by default with virtualenv, but not with venv.

**Comment by FFY00** [comment]
How does your `setup.py` look like? There's is no `extra_requires`, it is called `extras_require` and it's not a list like `setup_requires`.

Can you post the exact commands to reproduce?

It seems like you messed up the history by doing a merge. Can you look at reflog, do a hard reset to a previous state and then rebase on master? This should result in a clean git tree with just one commit on top of master. Let me know if you need help with the commands.

**Comment by ohsix** [comment]
what version of ubuntu and python3?

**Comment by whitequark** [comment]
@alanvgreen I believe you are hitting an issue with the way Debian ships Python packages. If you install `python3-wheel` from apt, do you still have this problem?

**Comment by alanvgreen** [comment]
@ohsix : from the bug report

~~~~
(life) osboxes@osboxes:~/life$ uname -a
Linux osboxes 5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
(life) osboxes@osboxes:~/life$ python --version
Python 3.7.5
(life) osboxes@osboxes:~/life$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
~~~~

**Comment by alanvgreen** [comment]
@FFY00 Thanks for your kind offer, I think I managed to straighten out my pull request. Let me know if not.

Here is a repro:

~~~~
osboxes@osboxes:~$ python3 -m venv test
osboxes@osboxes:~$ cd test
osboxes@osboxes:~/test$ . bin/activate
(test) osboxes@osboxes:~/test$ pip install nmigen
Collecting nmigen
  Downloading https://files.pythonhosted.org/packages/43/08/162d253c8d41460cffda0ca4d60f7fb075bb2b787b82089189c76a33f121/nmigen-0.2.tar.gz (144kB)
    100% |████████████████████████████████| 153kB 2.8MB/s 
Collecting Jinja2 (from nmigen)
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting pyvcd~=0.1.4 (from nmigen)
  Using cached https://files.pythonhosted.org/packages/01/3e/2ff169806a094365722f6670cc777f83bd93c56471ccc260cc5e0ba36b50/pyvcd-0.1.7-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from nmigen) (40.8.0)
Collecting MarkupSafe>=0.23 (from Jinja2->nmigen)
  Using cached https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting six (from pyvcd~=0.1.4->nmigen)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Building wheels for collected packages: nmigen
  Running setup.py bdist_wheel for nmigen ... error
  Complete output from command /home/osboxes/test/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-p6ju8i6j/nmigen/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-oeglfmeo --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for nmigen
  Running setup.py clean for nmigen
Failed to build nmigen
Installing collected packages: MarkupSafe, Jinja2, six, pyvcd, nmigen
  Running setup.py install for nmigen ... done
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 nmigen-0.2 pyvcd-0.1.7 six-1.14.0
(test) osboxes@osboxes:~/test$ 
~~~~

If I then attempt to `pip install nmigen` a second time, things look okay:
~~~~
(test) osboxes@osboxes:~/test$ pip install nmigen
Requirement already satisfied: nmigen in ./lib/python3.7/site-packages (0.2)
Requirement already satisfied: Jinja2 in ./lib/python3.7/site-packages (from nmigen) (2.11.2)
Requirement already satisfied: pyvcd~=0.1.4 in ./lib/python3.7/site-packages (from nmigen) (0.1.7)
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from nmigen) (40.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./lib/python3.7/site-packages (from Jinja2->nmigen) (1.1.1)
Requirement already satisfied: six in ./lib/python3.7/site-packages (from pyvcd~=0.1.4->nmigen) (1.14.0)
(test) osboxes@osboxes:~/test$ python
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nmigen import *
>>> 
~~~~

I don't know what to make of that - I wouldn't trust the installation.

Looking at https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies I'm not sure why extras_require is the right thing to use here. What did you have in mind?

**Comment by alanvgreen** [comment]
@whitequark It turns out that I already had python3-wheel installed. I can't recall whether I explicitly installed it before - it may have been a dependency of something else, but very likely it was something I tried while working through my problems.

At this stage, I'm quite happy for the resolution of this PR to be "use virtualenv, not venv" :)

**Comment by whitequark** [comment]
It looks like the [documentation for venv](https://docs.python.org/3/library/venv.html) describes it as deprecated since 3.6. Is that right?

**Comment by programmerjake** [comment]
> It looks like the [documentation for venv](https://docs.python.org/3/library/venv.html) describes it as deprecated since 3.6. Is that right?

only the `pyvenv` script was deprecated where `python -m venv` is the recommended replacement:
https://docs.python.org/dev/whatsnew/3.6.html#id8

**Comment by whitequark** [comment]
@alanvgreen If you're happy using virtualenv then I suggest closing this, since it seems very hard to reproduce. If someone manages to find a good solution here I'm happy to merge it as well.

**Comment by alanvgreen** [comment]
Yup. Closing, thanks all!

**Comment by graingert** [comment]
@alanvgreen try
```
pip install git+git://github.com/graingert/nmigen@c1a25974fcd757b21f3cbf9be26424be9d43bec0#egg=nmigen
```

**Comment by alanvgreen** [comment]
@graingert Yes, that seems to work for me:

~~~~
osboxes@osboxes:~$ python3 -m venv test
osboxes@osboxes:~$ cd test
osboxes@osboxes:~/test$ . bin/activate
(test) osboxes@osboxes:~/test$ pip install git+git://github.com/graingert/nmigen@4c6070d#egg=nmigen
Collecting nmigen from git+git://github.com/graingert/nmigen@4c6070d#egg=nmigen
  Cloning git://github.com/graingert/nmigen (to revision 4c6070d) to /tmp/pip-install-bzsob8tr/nmigen
  Did not find branch or tag '4c6070d', assuming revision or ref.
  Installing build dependencies ... done
Collecting pyvcd~=0.2.0 (from nmigen)
  Using cached https://files.pythonhosted.org/packages/95/44/1e4302b02fd5a5c65e2a3846b0a9468c7e3c9d52ba546d6ff1d17fa378a8/pyvcd-0.2.1-py2.py3-none-any.whl
Collecting Jinja2~=2.11 (from nmigen)
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2~=2.11->nmigen)
  Using cached https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Building wheels for collected packages: nmigen
  Running setup.py bdist_wheel for nmigen ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-ekr8zajb/wheels/7f/7f/14/1d74905917927f926962a87dc38dafdb57ececd753331b2d89
Successfully built nmigen
Installing collected packages: pyvcd, MarkupSafe, Jinja2, nmigen
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 nmigen-0.3.dev36+g4c6070d pyvcd-0.2.1
(test) osboxes@osboxes:~/test$ 
~~~~

**Comment by whitequark** [comment]
@alanvgreen Thanks for confirming! There are some issues with #358 that prevent merging it in the short term, but I'll make sure that this is fixed at some point. For now, please use `virtualenv`.

**Comment by whitequark** [comment]
@alanvgreen I fixed this properly in 7fca037f9c14974f499195171bb84c38ebddc1e1.

**Pull request closed without merging**
