### PR TITLE
Unify Xilinx platforms into a single class, support more devices

### LINKED ISSUE #552: Unify Xilinx platforms
The current approach for vendor files is to have one per series, which does not really work for Xilinx: the two facets of each Xilinx FPGA is the IOI type and the toolchain, both of which variously combine in each series. In IRC discussion, @mwkmwkmwk suggested that Xilinx platforms should be unified, and I decided to go forward with that plan specifically for Xilinx devices.

### PR DESCRIPTION
**Pull request by mwkmwkmwk**
This merges existing code, and also adds support for:

- Virtex, Virtex E (also known as Spartan 2, Spartan 2E)
- Virtex 2, Virtex 2 Pro
- Spartan 3, Spartan 3E (in addition to existing Spartan 3A, Spartan 3A
  DSP support)
- Virtex 4
- Virtex 5
- Virtex 6
- ISE synthesis for Series 7

Fixes #552.

### CODE REVIEW

**Comment by mwkmwkmwk** [comment]
Other notes:

- DDR handling was broken for most devices, this PR fixes it (I haven't fully tested it, mostly due to lack of hardware, but it ends up successfully emitting a bitstream, which is more than can be said for old code)
- the old imports are still available, but are just trivial aliases for the new unified class; should we slap a deprecation warning on them somehow?

**Comment by nickoe** [comment]
@mwkmwkmwk Just a heads up, this needs to be rebased after https://github.com/nmigen/nmigen/pull/584

**Comment by mwkmwkmwk** [comment]
Rebased.

@whitequark can we get this merged? I'd rather avoid having to do conflict resolution on this thing again.

**Comment by whitequark** [comment]
> can we get this merged? I'd rather avoid having to do conflict resolution on this thing again.

I'll merge this PR before any future changes to Xilinx platforms (and generally, soon).

**Comment by mwkmwkmwk** [comment]
Rebased once again, also added xck26 (per @DX-MON suggestion) and xcu* to the list

**Review by whitequark — APPROVED** [review]
LGTM. Thank you for this wonderful PR!

**Pull request merged**
